#!/bin/bash
#set -x

######################################################################
# Скрипт по автоматизации синхронизации сайтов на Drupal с продуктива
# на локальную систему.
#
#
#                                @author: JKey
#                                   site: http://software-radar.com
#                                 github: https://github.com/JKeySZR
######################################################################


#---------------------------------------------------------------------
#                                               КОНФИГУРАЦИЯ
#---------------------------------------------------------------------
# Путь до директории в которой хранятся конфиги по сайтам
SITE_CFG=sites.d

#---------------------------------------------------------------------
#   COLOR SECTION
#---------------------------------------------------------------------
CLR_NC='\e[0m' # No Color
CLR_WHITE='\e[1;37m'
CLR_BLACK='\e[0;30m'
CLR_BLUE='\e[0;34m'
CLR_LIGHT_BLUE='\e[1;34m'
CLR_GREEN='\e[0;32m'
CLR_LIGHT_GREEN='\e[1;32m'
CLR_CYAN='\e[0;36m'
CLR_LIGHT_CYAN='\e[1;36m'
CLR_RED='\e[0;31m'
CLR_LIGHT_RED='\e[1;31m'
CLR_PURPLE='\e[0;35m'
CLR_LIGHT_PURPLE='\e[1;35m'
CLR_BROWN='\e[0;33m'
CLR_YELLOW='\e[1;33m'
CLR_GRAY='\e[0;30m'
CLR_LIGHT_GRAY='\e[0;37m'

# Bold
CLR_B_Black='\e[1;30m'       # Black
CLR_B_Red='\e[1;31m'         # Red
CLR_B_Green='\e[1;32m'       # Green
CLR_B_Yellow='\e[1;33m'      # Yellow
CLR_B_Blue='\e[1;34m'        # Blue
CLR_B_Purple='\e[1;35m'      # Purple
CLR_B_Cyan='\e[1;36m'        # Cyan
CLR_B_White='\e[1;37m'       # White

# Underline
CLR_U_Black='\e[4;30m'       # Black
CLR_U_Red='\e[4;31m'         # Red
CLR_U_Green='\e[4;32m'       # Green
CLR_U_ellow='\e[4;33m'      # Yellow
CLR_U_Blue='\e[4;34m'        # Blue
CLR_U_Purple='\e[4;35m'      # Purple
CLR_U_Cyan='\e[4;36m'        # Cyan
CLR_U_White='\e[4;37m'       # White

# Background
CLR_BG_Black='\e[40m'       # Black
CLR_BG_Red='\e[41m'         # Red
CLR_BG_Green='\e[42m'       # Green
CLR_BG_Yellow='\e[43m'      # Yellow
CLR_BG_Blue='\e[44m'        # Blue
CLR_BG_Purple='\e[45m'      # Purple
CLR_BG_Cyan='\e[46m'        # Cyan
CLR_BG_White='\e[47m'       # White

# High Intensity
CLR_IBlack='\e[0;90m'       # Black
CLR_IRed='\e[0;91m'         # Red
CLR_IGreen='\e[0;92m'       # Green
CLR_IYellow='\e[0;93m'      # Yellow
CLR_IBlue='\e[0;94m'        # Blue
CLR_IPurple='\e[0;95m'      # Purple
CLR_ICyan='\e[0;96m'        # Cyan
CLR_IWhite='\e[0;97m'       # White

# Bold High Intensity
CLR_BI_Black='\e[1;90m'      # Black
CLR_BI_Red='\e[1;91m'        # Red
CLR_BI_Green='\e[1;92m'      # Green
CLR_BI_Yellow='\e[1;93m'     # Yellow
CLR_BI_Blue='\e[1;94m'       # Blue
CLR_BI_Purple='\e[1;95m'     # Purple
CLR_BI_Cyan='\e[1;96m'       # Cyan
CLR_BI_White='\e[1;97m'      # White

# High Intensity backgrounds
CLR_On_IBlack='\e[0;100m'   # Black
CLR_On_IRed='\e[0;101m'     # Red
CLR_On_IGreen='\e[0;102m'   # Green
CLR_On_IYellow='\e[0;103m'  # Yellow
CLR_On_IBlue='\e[0;104m'    # Blue
CLR_On_IPurple='\e[0;105m'  # Purple
CLR_On_ICyan='\e[0;106m'    # Cyan
CLR_On_IWhite='\e[0;107m'   # White



#---------------------------------------------------------------------
#    Функция поиска наличия файлов *.sql
#---------------------------------------------------------------------
function find_dump(){
  echo -e "${CLR_GREEN}[SQL] $DST_SITE_PATH ${CLR_NC}"
  i=0
  while read line
    do
      SITES[ $i ]="$line"
      echo "  [$i] - $line"
      (( i++ ))
  done < <(ls -1 $DST_SITE_PATH | grep -i sql)
}


i=0
while read line
do
    SITES[ $i ]="$line"
    SNAME=$(echo $line | sed 's/\.conf$//')
    echo "[$i] - $SNAME"    
    (( i++ ))
done < <(ls -1 $SITE_CFG | grep conf)

echo -en "${CLR_GREEN} Выберите нужный сайт: ${CLR_NC}"
read SITE
echo "Your answe $SITE"

# Подгружаем конфиг выбранного сайта
. $SITE_CFG/${SITES[$SITE]}

# Формируем  список к исключению при синхронизации
for i in "${EXCLUDE[@]}"
do
    EXCLUDES=$EXCLUDES" --exclude $i"
done

# Выводим информацию к ознакомлению
echo -e "${CLR_YELLOW}Server:     $SERVER ${CLR_NC}"
echo -e "${CLR_YELLOW}Источник:   $SRC_SITE_PATH ${CLR_NC}"
echo -e "${CLR_YELLOW}Назначение: $DST_SITE_PATH ${CLR_NC}"
echo -e "${CLR_YELLOW}Исключения: $EXCLUDES ${CLR_NC}"
echo -e "${CLR_YELLOW}Команды: $CMD_AFTER ${CLR_NC}"

# Какие следующие действия ? 

while true; do
    echo -e "${CLR_IRed} r - rsync remote to local   ${CLR_NC}"
    echo -e "${CLR_IRed} s - show SQL dump in folder $DST_SITE_PATH ${CLR_NC}"    
    echo -e "${CLR_IGreen} q - Exit   ${CLR_NC}"        
    echo -en "${CLR_IRed} Your choose?:  ${CLR_NC}"    
    read input
    case $input in
        [Ss]* ) find_dump; exit;;
        [Rr]* ) break;;
        [Qq]* ) exit;;
        * ) echo "Please select answer.";;
    esac
done


rsync -avP $EXCLUDES  $SERVER:$SRC_SITE_PATH  $DST_SITE_PATH

for CMD in "${CMD_AFTER[@]}"
do
    echo -e "${CLR_RED} Будет выполнена команда: $CMD  ${CLR_NC}"
    eval "$CMD"
done
